name: GitHub Actions Vercel Production Deployment

on:
  push:
    branches-ignore:
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install --force
      - name: run test
        run: npm test